---
title: "Furnace Usage"
format: html
editor: visual
---


- Examine data from honeywell thermostat
- Data are from emails giving monthly data on how many hours furnace ran, avg temperatures etc.

```{r}

suppressPackageStartupMessages(library(tidyverse, quietly = TRUE))
library(janitor)
library(skimr)
suppressPackageStartupMessages(library(plotly, quietly = TRUE))

# read in data (downloaded from google sheet)
hw <- readr::read_csv('./data/Honeywell_Heating_Usage .csv', show_col_types = FALSE) |>
  janitor::clean_names()

hw$month <- as.factor(hw$month)

```



# Plot timeseries of heating usage (hours) per month

```{r}

hw %>% ggplot(aes(date,heating_usage_hours)) +
  geom_col() +
  labs(title = "Heating Usage Per Month",
       x = "Month",
       y = "Heating Usage [hours]")


```


# Plot heating usage (hours) per month, grouped by month

```{r}

hw %>% ggplot(aes(month, heating_usage_hours, 
                  group = month, 
                  fill = as.factor(year))
              ) + 
  geom_col(position = 'dodge2')


```

```{r}

hw %>% 
  filter(!is.na(month)) |>
  mutate(year = as.factor(year)) |>
  ggplot(aes(year, heating_usage_hours, fill = year)) +
  geom_col(position = 'dodge2') +
  facet_wrap('month') +
  scale_x_discrete(guide = guide_axis(angle = 45)) 
```


# Boxplot of usage by month

```{r}
#| label: fig-heating-boxplot
#| fig-cap: "Boxplot of heating usage by month"

hw %>% 
  filter(!is.na(month)) |>
  ggplot(aes(month, heating_usage_hours)) +
  geom_boxplot(aes(group = month)) +
  labs(title = "Heating Usage Per Month",
       x = "Month",
       y = "Heating Usage [hours]")

```



# Plot usage vs temp
```{r}
#| label: fig-heating-vs-hightemp
#| fig-cap: "Heating Hours vs Average Low Temperature"

hw %>% ggplot(aes(avg_low_temp, heating_usage_hours)) +
  geom_point(size = 4, alpha = 0.25) +
  labs(title = "Heating Hours vs Temperature",
       x = "Avg Low Temperature",
       y = "Heating Usage [hours]")


```

```{r}

g <- hw %>% 
  mutate(year = as.factor(year)) |>
  ggplot(aes(avg_low_temp, heating_usage_hours)) +
  geom_point(size = 4, aes(colour = year) ) +
  labs(title = "Heating Hours vs Temperature",
       x = "Avg Low Temperature",
       y = "Heating Usage [hours]")


ggplotly(g)

```

# Plot usage vs temp separately by year

```{r}

g <- hw %>% 
  filter(!is.na(year)) |>
  filter(month %in% c(9,10,11,12,1,2,3,4,5,6)) |>
  ggplot(aes(avg_low_temp, heating_usage_hours)) +
  geom_point(size = 3, alpha = 0.3) +
  facet_wrap('year') +
  ylim(range(hw$heating_usage_hours, na.rm = TRUE)) +
  xlim(range(hw$avg_low_temp, na.rm = TRUE))


ggplotly(g)
```


```{r}

hw %>% group_by(year) |>
  summarise(totaluse = sum(heating_usage_hours)) %>% 
  ggplot(aes(year, totaluse)) +
  geom_col()

```


```{r}

hw %>% group_by(month) %>% 
  summarise(avg = mean(heating_usage_hours, na.rm = TRUE),
            min = min(heating_usage_hours, na.rm = TRUE),
            max = max(heating_usage_hours, na.rm = TRUE)) 
```

